{{- if .Values.configMaps }}
  {{- range $name, $configMap := .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
data:
  {{- range $key, $value := $configMap }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
---
{{- end }}
  {{- end }}