name: menu-v2
image:
  repository: miguelarmasabt/menu
  tag: "v2.0.1"
  pullPolicy: IfNotPresent
ports:
  containerPort: 8016
  nodePort: 30016
replicas: 1

configMaps:
  mysql-domain: "mysql-db:3306"
  mysql-username: "bbq_user"
  product-domain: "product-v1:8017"
  java-opts: "-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dquarkus-profile=dev"

secrets:
  MYSQL_PASSWORD: "qwerty"

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"

livenessProbe:
  path: /actuator/health/liveness
  port: 8016
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  path: /actuator/health/readiness
  port: 8016
  initialDelaySeconds: 30
  periodSeconds: 30
