name: postgres-db
image:
  repository: postgres
  tag: "latest"
  pullPolicy: IfNotPresent
ports:
  containerPort: 5432
  nodePort: 30032
replicas: 1

secrets:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "qwerty"

initdb:
  value: initdb.sh

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"

namespace: restaurant
helmTemplate: database

docker:
  hostPort: 5432
  dependencies: none
  volumes: ./../environment/postgres-db/init:/docker-entrypoint-initdb.d;./../environment/postgres-db/data:/data/db