---
# Source: generic-backend-chart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
type: Opaque
data:
    POSTGRESQL_PASSWORD: "cXdlcnR5"
---
# Source: generic-backend-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-domain
data:
    value: "config-server-v1:8888"
---
# Source: generic-backend-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: java-opts
data:
    value: "-Xms256M -Xmx256M"
---
# Source: generic-backend-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-domain
data:
    value: "kafka-server:9093"
---
# Source: generic-backend-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-domain
data:
    value: "postgres-db:5432"
---
# Source: generic-backend-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-username
data:
    value: "bbq_user"
---
# Source: generic-backend-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-domain
data:
    value: "product-v1:8017"
---
# Source: generic-backend-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: invoice-service
  labels:
    app: invoice-service
spec:
  type: NodePort
  selector:
    app: invoice-service
  ports:
    - name: invoice-service
      port: 8014
      nodePort: 30014
---
# Source: generic-backend-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-service
  labels:
    app: invoice-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-service
  template:
    metadata:
      labels:
        app: invoice-service
    spec:
      containers:
        - name: invoice-service
          image: "miguelarmasabt/invoice:v1.0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8014

          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8014
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8014
            initialDelaySeconds: 30
            periodSeconds: 30

          env:
              - name: VALUE
                valueFrom:
                  configMapKeyRef:
                    name: config-server-domain
                    key: value
              - name: VALUE
                valueFrom:
                  configMapKeyRef:
                    name: java-opts
                    key: value
              - name: VALUE
                valueFrom:
                  configMapKeyRef:
                    name: kafka-domain
                    key: value
              - name: VALUE
                valueFrom:
                  configMapKeyRef:
                    name: postgresql-domain
                    key: value
              - name: VALUE
                valueFrom:
                  configMapKeyRef:
                    name: postgresql-username
                    key: value
              - name: VALUE
                valueFrom:
                  configMapKeyRef:
                    name: product-domain
                    key: value
              - name: POSTGRESQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgresql
                    key: POSTGRESQL_PASSWORD
