name: payment-v1
image:
  repository: miguelarmasabt/payment
  tag: "v1.0.1"
  pullPolicy: IfNotPresent
ports:
  containerPort: 8015
  nodePort: 30015
replicas: 1

configMaps:
  config-server-domain: "config-server-v1:8888"
  mysql-domain: "mysql-db:3306"
  mysql-username: "bbq_user"
  kafka-domain: "kafka-server:9093"
  create-topics: "true"
  java-opts: "-Xms256M -Xmx256M"

secrets:
  MYSQL_PASSWORD: "qwerty"

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"

livenessProbe:
  path: /actuator/health/liveness
  port: 8015
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  path: /actuator/health/readiness
  port: 8015
  initialDelaySeconds: 30
  periodSeconds: 30

namespace: restaurant
helmTemplate: with-health

docker:
  hostPort: 8015
  dependencies: config-server-v1;mysql-db;kafka-server
  volumes: none