configuration:
  error-messages:
    enabled: false
    messages:
      Default: No hemos podido realizar tu operación. Estamos trabajando para solucionar el inconveniente.

  obfuscation:
    body-fields: []
    headers: []

kafka-broker:
  topic:
    invoice: invoice-topic
    payment: paid-topic

spring:
  kafka:
    bootstrap-servers: ${KAFKA_DOMAIN:localhost:9092}
    consumer:
      group-id: bbq
    properties:
      spring:
        kafka:
          consumer:
            auto-offset-reset: earliest #latest
    admin:
      properties:
        spring.kafka.admin.properties:
          auto.create.topics.enable: ${CREATE_TOPICS:false}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none #create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true

  datasource:
    url: jdbc:mysql://${MYSQL_DOMAIN:127.0.0.1:3306}/db_payments?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:bbq_user}
    password: ${MYSQL_PASSWORD:qwerty}