name: mock-service-v1
image:
  repository: miguelarmasabt/mock-service
  tag: "v1.0.1"
  pullPolicy: IfNotPresent
ports:
  containerPort: 8021
  nodePort: 30020
replicas: 1

configMaps:
  mock-port: "8021"
  java-opts: "-Xms256M -Xmx256M"

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"

livenessProbe:
  path: /actuator/health/liveness
  port: 8020
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  path: /actuator/health/readiness
  port: 8020
  initialDelaySeconds: 30
  periodSeconds: 30

namespace: restaurant
helmTemplate: with-health

docker:
  hostPort: 8020
  dependencies: none