name: mongo-db
image:
  repository: mongo
  tag: "latest"
  pullPolicy: IfNotPresent
ports:
  containerPort: 27017
  nodePort: 30717
replicas: 1

secrets:
  MONGO_INITDB_ROOT_USERNAME: "bbq-user"
  MONGO_INITDB_ROOT_PASSWORD: "qwerty"
  MONGO_INITDB_DATABASE: "tablePlacement"

initdb:
  value: initdb.js

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"

namespace: restaurant
helmTemplate: database

docker:
  hostPort: 27017
  dependencies: none
  volumes: ./../environment/mongo-db/init:/docker-entrypoint-initdb.d;./../environment/mongo-db/data:/data/db