name: rules-processor-v1
image:
  repository: miguelarmasabt/rules-processor
  tag: "v1.0.1"
  pullPolicy: IfNotPresent
ports:
  containerPort: 8019
  nodePort: 30019
replicas: 1

configMaps:
  config-server-domain: "config-server-v1:8888"
  java-opts: "-Xms256M -Xmx256M"

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"

livenessProbe:
  path: /actuator/health/liveness
  port: 8019
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  path: /actuator/health/readiness
  port: 8019
  initialDelaySeconds: 30
  periodSeconds: 30

namespace: restaurant
helmTemplate: with-health

docker:
  hostPort: 8019
  dependencies: config-server-v1
  volumes: none