{{- if .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
data:
  {{- range $key, $value := .Values.configMaps }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
  {{- end }}
---