name: auth-adapter-v1
image:
  repository: miguelarmasabt/auth-adapter
  tag: "v1.0.1"
  pullPolicy: IfNotPresent
ports:
  containerPort: 8011
  nodePort: 30011
replicas: 1

configMaps:
  java-opts: "-Xms256M -Xmx256M"

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"

livenessProbe:
  path: /actuator/health/liveness
  port: 8011
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  path: /actuator/health/readiness
  port: 8011
  initialDelaySeconds: 30
  periodSeconds: 30
