name: product-v1
image:
  repository: miguelarmasabt/product
  tag: "v1.0.1"
  pullPolicy: IfNotPresent
ports:
  containerPort: 8017
  nodePort: 30017
replicas: 1

configMaps:
  mysql-host: "mysql-db:3306"
  mysql-username: "bbq_user"
  database: "db_products"

secrets:
  MYSQL_PASSWORD: "qwerty"

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"

livenessProbe:
  path: /actuator/health/liveness
  port: 8017
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  path: /actuator/health/readiness
  port: 8017
  initialDelaySeconds: 30
  periodSeconds: 30
