name: kafka-server
image:
  repository: confluentinc/cp-kafka
  tag: "7.3.2"
  pullPolicy: IfNotPresent
ports:
  containerPort: 9092
  nodePort: 30092
replicas: 1

configMaps:
  kafka-advertised-listeners: "INTERNAL://kafka-server:9093,EXTERNAL://-127.0.0.1:9092,DOCKER://host.docker.internal:29092"
  kafka-listener-security-protocol-map: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT"
  kafka-inter-broker-listener-name: "INTERNAL"
  kafka-zookeeper-connect: "zookeeper-server:2181"
  kafka-broker-id: "1"
  kafka-log4j-loggers: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
  kafka-offsets-topic-replication-factor: "1"
  kafka-transaction-state-log-replication-factor: "1"
  kafka-transaction-state-log-min-isr: "1"
  kafka-jmx-port: "9999"
  kafka-jmx-hostname: "127.0.0.1"
  kafka-authorizer-class-name: "kafka.security.authorizer.AclAuthorizer"
  kafka-allow-everyone-if-no-acl-found: "true"

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi"
    cpu: "1"

namespace: restaurant
helmTemplate: default

docker:
  hostPort: 9092
  dependencies: zookeeper-server