version: '3.1'

services:
  config-server-v1:
    container_name: config-server-v1
    image: miguelarmasabt/config-server:v1.0.1
    restart: always
    environment: 
      - JAVA_OPTS=-Xms256M -Xmx256M
    
    
    networks:
      - dev_environment
    ports:
      - "8888:8888"

  api-gateway-v1:
    container_name: api-gateway-v1
    image: miguelarmasabt/api-gateway:v1.0.1
    restart: always
    environment: 
      - ORDER_HUB_DOMAIN=order-hub-v1:8018
      - ENABLE_AUTH=false
      - AUTH_ADAPTER_DOMAIN=auth-adapter-v1:8011
      - JAVA_OPTS=-Xms256M -Xmx256M
    
    
    networks:
      - dev_environment
    ports:
      - "8010:8010"

  auth-adapter-v1:
    container_name: auth-adapter-v1
    image: miguelarmasabt/auth-adapter:v1.0.1
    restart: always
    environment: 
      - KEYCLOAK_DOMAIN=keycloak-server:8080
      - KEYCLOAK_KEY_RS256=mH6KTBOtG3B8_UcrOvA6zPn23SdGeqpp5YOp-MHR0Fo
      - JAVA_OPTS=-Xms256M -Xmx256M
    
    
    networks:
      - dev_environment
    ports:
      - "8011:8011"

  menu-v1:
    container_name: menu-v1
    image: miguelarmasabt/menu:v1.0.1
    restart: always
    environment: 
      - CONFIG_SERVER_DOMAIN=config-server-v1:8888
      - MYSQL_DOMAIN=mysql-db:3306
      - MYSQL_USERNAME=bbq_user
      - MYSQL_PASSWORD=qwerty
      - PRODUCT_DOMAIN=product-v1:8017
      - JAVA_OPTS=-Xms256M -Xmx256M
    depends_on:
      - config-server-v1
      - mysql-db
    
    networks:
      - dev_environment
    ports:
      - "8012:8012"

  table-placement-v1:
    container_name: table-placement-v1
    image: miguelarmasabt/table-placement:v1.0.1
    restart: always
    environment: 
      - CONFIG_SERVER_DOMAIN=config-server-v1:8888
      - MONGODB_URL=mongodb://bbq-user:qwerty@mongo-db:27017/tablePlacement
      - JAVA_OPTS=-Xms256M -Xmx256M
    depends_on:
      - config-server-v1
      - mongo-db
    
    networks:
      - dev_environment
    ports:
      - "8013:8013"

  invoice-v1:
    container_name: invoice-v1
    image: miguelarmasabt/invoice:v1.0.1
    restart: always
    environment: 
      - CONFIG_SERVER_DOMAIN=config-server-v1:8888
      - KAFKA_DOMAIN=kafka-server:9093
      - POSTGRESQL_DOMAIN=postgres-db:5432
      - POSTGRESQL_USERNAME=bbq_user
      - POSTGRESQL_PASSWORD=qwerty
      - PRODUCT_DOMAIN=product-v1:8017
      - JAVA_OPTS=-Xms256M -Xmx256M
    depends_on:
      - config-server-v1
      - postgres-db
      - kafka-server
    
    networks:
      - dev_environment
    ports:
      - "8014:8014"

  payment-v1:
    container_name: payment-v1
    image: miguelarmasabt/payment:v1.0.1
    restart: always
    environment: 
      - CONFIG_SERVER_DOMAIN=config-server-v1:8888
      - MYSQL_DOMAIN=mysql-db:3306
      - MYSQL_USERNAME=bbq_user
      - MYSQL_PASSWORD=qwerty
      - KAFKA_DOMAIN=kafka-server:9093
      - CREATE_TOPICS=true
      - JAVA_OPTS=-Xms256M -Xmx256M
    depends_on:
      - config-server-v1
      - mysql-db
      - kafka-server
    
    networks:
      - dev_environment
    ports:
      - "8015:8015"

  menu-v2:
    container_name: menu-v2
    image: miguelarmasabt/menu:v2.0.1
    restart: always
    environment: 
      - MYSQL_DOMAIN=mysql-db:3306
      - PRODUCT_DOMAIN=product-v1:8017
      - MYSQL_USERNAME=bbq_user
      - MYSQL_PASSWORD=qwerty
      - JAVA_OPTS=-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dquarkus-profile=dev
    depends_on:
      - mysql-db
    
    networks:
      - dev_environment
    ports:
      - "8016:8016"

  product-v1:
    container_name: product-v1
    image: miguelarmasabt/product:v1.0.1
    restart: always
    environment: 
      - MYSQL_HOST=mysql-db:3306
      - MYSQL_USERNAME=bbq_user
      - MYSQL_PASSWORD=qwerty
      - DATABASE=db_products
    depends_on:
      - mysql-db
    
    networks:
      - dev_environment
    ports:
      - "8017:8017"

  order-hub-v1:
    container_name: order-hub-v1
    image: miguelarmasabt/order-hub:v1.0.1
    restart: always
    environment: 
      - CONFIG_SERVER_DOMAIN=config-server-v1:8888
      - MENU_V1_DOMAIN=menu-v1:8012
      - MENU_V2_DOMAIN=menu-v2:8016
      - TABLE_PLACEMENT_DOMAIN=table-placement-v1:8013
      - INVOICE_DOMAIN=invoice-v1:8014
      - JAVA_OPTS=-Xms256M -Xmx256M
    depends_on:
      - config-server-v1
      - redis-server
    
    networks:
      - dev_environment
    ports:
      - "8018:8018"

  keycloak-server:
    container_name: keycloak-server
    image: jboss/keycloak:16.0.0
    restart: always
    environment: 
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=H2
    
    
    networks:
      - dev_environment
    ports:
      - "8091:8080"

  redis-server:
    container_name: redis-server
    image: redis:latest
    restart: always
    environment: 
      - DUMMY=dummy
    
    
    networks:
      - dev_environment
    ports:
      - "6379:6379"

  kafka-server:
    container_name: kafka-server
    image: confluentinc/cp-kafka:7.3.2
    restart: always
    environment: 
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-server:9093,EXTERNAL://-127.0.0.1:9092,DOCKER://host.docker.internal:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_LOG4J_LOGGERS=kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_JMX_PORT=9999
      - KAFKA_JMX_HOSTNAME=127.0.0.1
      - KAFKA_AUTHORIZER_CLASS_NAME=kafka.security.authorizer.AclAuthorizer
      - KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true
    depends_on:
      - zookeeper-server
    
    networks:
      - dev_environment
    ports:
      - "9092:9092"

  zookeeper-server:
    container_name: zookeeper-server
    image: confluentinc/cp-zookeeper:7.3.2
    restart: always
    environment: 
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_SERVERS=zookeeper-server:2888:3888
    
    
    networks:
      - dev_environment
    ports:
      - "2181:2181"

  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=qwerty
      - TZ=UTC
    
    volumes:
      - ./../environment/mysql-db/init:/docker-entrypoint-initdb.d
      - ./../environment/mysql-db/data:/data/db
    networks:
      - dev_environment
    ports:
      - "3306:3306"

  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    
    volumes:
      - ./../environment/postgres-db/init:/docker-entrypoint-initdb.d
      - ./../environment/postgres-db/data:/data/db
    networks:
      - dev_environment
    ports:
      - "5432:5432"

  mongo-db:
    container_name: mongo-db
    image: mongo:latest
    restart: always
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=bbq-user
      - MONGO_INITDB_ROOT_PASSWORD=qwerty
      - MONGO_INITDB_DATABASE=tablePlacement
    
    volumes:
      - ./../environment/mongo-db/init:/docker-entrypoint-initdb.d
      - ./../environment/mongo-db/data:/data/db
    networks:
      - dev_environment
    ports:
      - "27017:27017"


networks:
  dev_environment:
    driver: bridge
    #activate ipv6
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    #IP Adress Manager
    ipam:
      driver: default
      config:
        -
          subnet: 172.16.232.0/24
          gateway: 172.16.232.1
        -
          subnet: "2001:3974:3979::/64"
          gateway: "2001:3974:3979::1"
